Change WORKDIR in script, not relying on docker run -w by user
super-linter/super-linter pull request #4821
Opened 2023-10-31 01:30 UTC by kftsehk

Fixes #4459

## Proposed Changes

pushd to `$DEFAULT_WORKSPACE` before resolving files

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2023-10-31 08:14 UTC, ferrarimarco requested changes
Thanks for this PR! Mostly ok, we probably need some more documentation.

Thanks!

2023-10-31 08:14 UTC, ferrarimarco commented on lib/linter.sh
> +    pushd "$GITHUB_WORKSPACE" >/dev/null || exit
- Can you use `${GITHUB_WORKSPACE}` for consistency?
- Can you add a comment to explain what you're doing, and why not using a `cd`?
- Can you exit with an error if the directory doesn't exist?

2023-10-31 08:15 UTC, ferrarimarco commented on lib/linter.sh
> +    pushd "$GITHUB_WORKSPACE" >/dev/null || exit
Also, how would this change impact users? Shall they do something different?

2023-10-31 09:02 UTC, kftsehk commented on lib/linter.sh
> +    pushd "$GITHUB_WORKSPACE" >/dev/null || exit
Sorry that the typo of fixes #4459 instead of #4495 had confused you.

This fix applies to `RUN_LOCAL=true`

File resolver runs in `WORKDIR` defined in `Dockerfile`, it does not define one, and defaults to `/`. The reason of #4495 is the file resolver scan `$PWD = /` for code, which contains `/root /bin /lib` etc, all of which results in `fatal: not a git repository (or any of the parent directories): .git`, until it finds `/tmp/lint`

Now `docker run -w /tmp/lint` is required to suppress the above error message even if user is not aware of `DEFAULT_WORKSPACE` config

https://github.com/super-linter/super-linter/blob/c3ac3aa5d9c14fd80edc78eb3c4af8bea0849fa6/README.md?plain=1#L284


There is probably no reason to define `WORKDIR` in Dockerfile, as `DEFAULT_WORKSPACE` can be changed at runtime if user wish to mount elsewhere other than `/tmp/lint` via `docker run -v /host/filesystem/my/code:<somewhere-inside-container-not-tmp-lint>`

So the solution imo is to change to evaluated `$GITHUB_WORKSPACE` right after its evaluation

> * Can you use `${GITHUB_WORKSPACE}` for consistency?

is used in commit

> * Can you add a comment to explain what you're doing, and why not using a `cd`?

`pushd` to have a backup of docker's `WORKDIR` if ever needed, imo obvious enough to notice here that `info "Linting all files in mapped directory:[${GITHUB_WORKSPACE}]"` has to go into directory `$GITHUB_WORKSPACE`

> * Can you exit with an error if the directory doesn't exist?

https://github.com/super-linter/super-linter/blob/3d1ea8f5adeb62068bf8ecb318aa732541bb8de2/lib/linter.sh#L499-L501

Existence checked here, I guess it might fail for some strange reason like missing `+x` file permission

> Also, how would this change impact users? Shall they do something different?

No longer need to type docker flag `-w /tmp/lint`, they shall still use it this way but it won't do anything good or bad.

2023-10-31 09:52 UTC, ferrarimarco commented on lib/linter.sh
> +    pushd "$GITHUB_WORKSPACE" >/dev/null || exit
Thanks for the explanation!

I think I still see `$GITHUB_WORKSPACE` instead of `${GITHUB_WORKSPACE}`. :)

2023-11-04 08:35 UTC, ferrarimarco approved these changes
LGTM. @zkoppert and @Hanse00  probably want to have a look because it changes things a bit under the hood.

2023-11-05 04:29 UTC, zkoppert approved these changes
That's for explaining the changes. I looked through our building documentation and don't see anything that needs to change there to match this code change.

2023-11-05 05:01 UTC, merged