Allow to overwrite `PHP_PHPCS_FILE_NAME` value
super-linter/super-linter pull request #4849
Opened 2023-11-10 15:24 UTC by goetzc

The PHP CodeSniffer linter itself allows different configuration file names:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

> Note: If multiple default configuration files are found, PHP_CodeSniffer will select one using the following order: `.phpcs.xml`, `phpcs.xml`, `.phpcs.xml.dist`, `phpcs.xml.dist`

This non-breaking change allow to select the name for the appropriate local file name.

## Proposed Changes

1. Allow to choose a different configuration file name.

## Readiness Checklist

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2023-11-10 18:05 UTC, ferrarimarco requested changes
Thanks for this PR! A small doc update, and we shall be good to go.

2023-11-10 18:05 UTC, ferrarimarco commented on lib/linter.sh
> +PHP_PHPCS_FILE_NAME="${PHP_PHPCS_FILE_NAME:-phpcs.xml}"
Can you add the relevant entry in the environment vars table in the README?

2023-11-10 18:28 UTC, goetzc commented on lib/linter.sh
> +PHP_PHPCS_FILE_NAME="${PHP_PHPCS_FILE_NAME:-phpcs.xml}"
Sure, that makes sense!

2023-11-10 18:51 UTC, goetzc commented on lib/linter.sh
> +PHP_PHPCS_FILE_NAME="${PHP_PHPCS_FILE_NAME:-phpcs.xml}"
Done

2023-11-12 20:21 UTC, ferrarimarco approved these changes

2023-11-15 05:51 UTC, zkoppert approved these changes

2023-11-15 07:29 UTC, merged