Test local run with non-default general settings
super-linter/super-linter pull request #4955
Opened 2023-12-06 23:03 UTC by kftsehk

Test coverage related to #4952 #4954, did not fix the issue

## Proposed Changes

**Scope**

Guarentees super-linter builds can complete linting for local run in various non-default scenarios

Test coverage for `RUN_LOCAL=true` in CI/CD for non-default general settings
- Non-default Workspace: `DEFAULT_WORKSPACE`
- Git Related Env: `IGNORE_GENERATED_FILES`, `IGNORE_GITIGNORED_FILES`, `VALIDATE_ALL_CODEBASE`
- Find Algorithm: `USE_FIND_ALGORITHM`
- Non Git-tracked Directory: directory without a `.git` folder
- Experimental Features: `EXPERIMENTAL_BATCH_WORKER`

**Out of scope**

There is NO assertion for correctness of the implementation, for example
- it does not assert `find` command is used instead of `git diff` when `USE_FILE_ALGORITHM=true`
- it does not assert `.gitignored` files are not linted when `IGNORE_GITIGNORED_FILES=true`
- likewise for others

These shall be tested as part of test suite or in other tests if necessary.

## Readiness Checklist

### Author/Contributor

- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.

### Reviewing Maintainer

- [ ] Label as `breaking` if this is a large, fundamental change.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2023-12-06 23:06 UTC, kftsehk commented
It is an expected behavior to have failing CI/CD before issues such as #4952 #4954 are fixed, as the tests are designed to run code-paths previously not tested, and involved in the above issues.

2023-12-07 06:47 UTC, ferrarimarco commented
Thanks for this PR!

While we iterate on this one, can you remove the step to run `USE_FIND_ALGORITHM=true`? I'm taking care of it in #4953

Thanks!

2023-12-12 04:48 UTC, kftsehk commented
seem to conflict with migration of #4982

2023-12-12 07:44 UTC, ferrarimarco requested changes
@kftsehk In #4982, we're refactoring the build process to reduce duplication. Can you kindly refactor this PR my moving the logic to run these additional test cases to the Makefile? Hopefully it's not going to be too much work :)

Thanks a lot!

2023-12-12 07:55 UTC, kftsehk commented
sure will wait for your PR go through and update it

On Tue, 12 Dec 2023 at 3:44 PM, Marco Ferrari ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @kftsehk <https://github.com/kftsehk> In #4982
> <https://github.com/super-linter/super-linter/pull/4982>, we're
> refactoring the build process to reduce duplication. Can you kindly
> refactor this PR my moving the logic to run these additional test cases to
> the Makefile? Hopefully it's not going to be too much work :)
>
> Thanks a lot!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/super-linter/super-linter/pull/4955#pullrequestreview-1776832644>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE6YIWAR5RNNUB3CCWBK673YJADPDAVCNFSM6AAAAABAKEPTM6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZWHAZTENRUGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-20 16:51 UTC, kftsehk commented
pipeline failed by unrelated issue:
jscpd liniting on `.github/workflows/cd.yml` and report failure issue creation as duplicated code

2023-12-20 16:59 UTC, ferrarimarco requested changes

2023-12-20 16:59 UTC, ferrarimarco commented on Makefile
> -		-v "$(CURDIR)/.github":/tmp/lint/.github \
This is needed, otherwise super-linter will not find rules files in `.github/linters`.

2023-12-20 16:59 UTC, ferrarimarco commented on Makefile
> +		-v "$(CURDIR)/.github:/tmp/not-default-workspace" \
Refactoring this to `-v $(CURDIR)/.github:/tmp/not-default-workspace/.github` should fix the issues with JSCPD.

2023-12-20 16:59 UTC, ferrarimarco commented on Makefile
> -		-v "$(CURDIR)/.github":/tmp/lint/.github \
Can you please revert this change?

2024-01-02 17:39 UTC, ferrarimarco requested changes

2024-01-02 17:39 UTC, ferrarimarco commented on Makefile
> +		-e VALIDATE_ALL_CODEBASE=false \
Can you set this to `true`?

2024-01-16 08:56 UTC, ferrarimarco approved these changes
@kftsehk thanks for this PR. I've updated it to address review comments, and should be good to go. Let's wait for the CI jobs to complete.

2024-01-16 09:13 UTC, ferrarimarco approved these changes

2024-01-16 09:23 UTC, merged