docs: fix README.md for slim action
super-linter/super-linter pull request #5080
Opened 2024-01-01 07:58 UTC by chrisjohnson00

## Proposed Changes

Fix to the README for how to run this action using the `slim` configuration.

## Readiness Checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [X] I included all the needed documentation for this change.
- [X] I provided the necessary tests.
- [X] I squashed all the commits into a single commit.
- [X] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [X] If this is a breaking change, write upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-01-01 17:36 UTC, chrisjohnson00 commented
Here is where I'm using it 

https://github.com/chrisjohnson00/plex-sad-search/blob/16b70b09cb4396bd6437c550b1d33b0a682ae96b/.github/workflows/ci.yml#L151

AFAIK, the standard usage reference is correct. However, I don't use it since the container pull takes so dang long. 

I will check (on phone now) later.

2024-01-01 17:45 UTC, ferrarimarco requested changes
One small change and we should be good to go.

2024-01-01 17:45 UTC, ferrarimarco commented on README.md
>  - `standard`: `super-linter/super-linter:[VERSION]`: includes all supported linters.
Can you please refactor this one to: `super-linter/super-linter@[VERSION]`?

Thanks!

2024-01-01 21:41 UTC, chrisjohnson00 commented on README.md
>  - `standard`: `super-linter/super-linter:[VERSION]`: includes all supported linters.
oh yeah, good catch

2024-01-02 17:05 UTC, ferrarimarco approved these changes

2024-01-02 17:09 UTC, ferrarimarco commented
@chrisjohnson00 last thing to do: I've rebased this on the latest `main`, but we also need this to be a single commit. Can you please squash the two commits in a single one? Thanks a lot!

2024-01-02 18:03 UTC, chrisjohnson00 commented
> @chrisjohnson00 last thing to do: I've rebased this on the latest `main`, but we also need this to be a single commit. Can you please squash the two commits in a single one? Thanks a lot!

Done!

2024-01-02 18:32 UTC, merged