fix: install zlib from alpine packages
super-linter/super-linter pull request #5317
Opened 2024-02-23 00:18 UTC by harryzcy

# Proposed changes

Running `install-glibc.sh` failed in ARM64, because arch linux packages doesn't offer a build for `arm64`. i.e. `https://www.archlinux.org/packages/core/arm64/zlib/download` returns a 404.

Related to #5070

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-02-23 11:25 UTC, ferrarimarco requested changes
Thanks for this PR!

There are a couple of things to check.

Let's see what the CI says :)

2024-02-23 11:25 UTC, ferrarimarco commented on scripts/install-glibc.sh
> -apk add --no-cache --virtual .glibc-build-deps \
Can you leave the `.glibc-build-deps` identifier? We may need it in case we decide to remove build-time deps.

2024-02-23 11:25 UTC, ferrarimarco commented on scripts/install-glibc.sh
> +  zlib-dev
Is there a non `dev` version of this package that's hopefully smaller?

2024-02-23 11:27 UTC, ferrarimarco commented on scripts/install-glibc.sh
>  mkdir /tmp/libz
We don't need this anymore, I suppose.

2024-02-23 12:31 UTC, ferrarimarco commented on scripts/install-glibc.sh
> +  zstd \
Can you please keep alphabetical ordering for these packages?

2024-02-23 18:24 UTC, ferrarimarco commented on scripts/install-glibc.sh
> -case $TARGETARCH in
Are you sure that this glibc distribution is compatible with arm64?

2024-02-24 01:06 UTC, harryzcy commented on scripts/install-glibc.sh
> -case $TARGETARCH in
It installs with no errors on arm64

2024-02-24 19:08 UTC, ferrarimarco commented on scripts/install-glibc.sh
> -case $TARGETARCH in
Does it run tho? What is the result of `make test-linters` ? :)

2024-02-24 23:06 UTC, harryzcy commented on scripts/install-glibc.sh
> -case $TARGETARCH in
Thanks for reporting. From https://github.com/sgerrand/docker-glibc-builder, it looks like arm64 is not supported.. I'll try to find another solution

2024-02-26 01:17 UTC, harryzcy commented on scripts/install-glibc.sh
> -case $TARGETARCH in
Is it ok to use the [`gcompat`](https://pkgs.alpinelinux.org/packages?name=gcompat&branch=edge&repo=&arch=&maintainer=) compatibility layer, instead of the actual glibc? Otherwise, I will try to rebuild one from [docker-glibc-builder](https://github.com/sgerrand/docker-glibc-builder)

2024-02-26 08:29 UTC, ferrarimarco commented on scripts/install-glibc.sh
> -case $TARGETARCH in
Hi! We didn't try using `gcompat`, but it's worth trying, I suppose! If it works, that would make the build easier to maintain because we can just install that from the Alpine package repository. I would suggest trying this in another PR, and revert the this change (but keep the `zlib` changes), so we can go ahead and merge this.

WDYT?

2024-02-26 23:17 UTC, harryzcy commented on scripts/install-glibc.sh
> -case $TARGETARCH in
> I would suggest trying this in another PR

Sent #5334 

> revert this particular change (but keep the rest of changes about `zlib`)

I didn't add the change here

2024-02-27 10:12 UTC, ferrarimarco commented on scripts/install-glibc.sh
> -case $TARGETARCH in
I mean: can you please revert the change that checks for platforms? Thanks!

and thanks for the new PR!

2024-02-28 08:56 UTC, ferrarimarco commented
@harryzcy after looking at the linter failure (see below), I think we should remove the platform check `switch`, as you did initially :)

```
  In /github/workspace/scripts/install-glibc.sh line 10:
    target=arm64
    ^----^ SC2034 (warning): target appears unused. Verify use (or export if used externally).
```

2024-02-28 16:30 UTC, harryzcy commented
> @harryzcy after looking at the linter failure (see below), I think we should remove the platform check `switch`, as you did initially, you were right! :)
> 
> ```
>   In /github/workspace/scripts/install-glibc.sh line 10:
>     target=arm64
>     ^----^ SC2034 (warning): target appears unused. Verify use (or export if used externally).
> ```

@ferrarimarco Fixed.

2024-02-29 07:09 UTC, ferrarimarco approved these changes

2024-02-29 12:56 UTC, merged