Find go.mod based on Go files
super-linter/super-linter pull request #5345
Opened 2024-03-02 10:45 UTC by harryzcy

# Proposed changes

Close #5292

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-03-04 17:25 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      while [ "${dir_name}" != "$(dirname ${GITHUB_WORKSPACE})" ] && [ "${dir_name}" != "/" ]; do
Can you please double-quote `${GITHUB_WORKSPACE}` ?

2024-03-04 17:25 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +          echo "${dir_name}/go.mod" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO_MODULES"
What if we already added this `go.mod` file?

2024-03-04 17:25 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      # find go.mod
Can you add some `debug` statements so we can follow what's happening?

2024-03-04 17:25 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      dir_name="${FILE_DIR_NAME}"
Can you add `local dir_name` before this assignment?

2024-03-04 17:26 UTC, ferrarimarco commented
Thanks for this PR! A few small things to check.

2024-03-10 22:52 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +          echo "${dir_name}/go.mod" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO_MODULES"
I implemented a solution in 4992fa4, please review it. Thanks

2024-03-11 19:39 UTC, ferrarimarco commented
Thanks! A small thing to fix:

```sh
            if [ ! grep -Fxq \\"${go_mod_filename}\\" \\"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO_MODULES\\" ]; then
            ^-- SC1009 (info): The mentioned syntax error was in this if expression.
               ^-- SC1073 (error): Couldn't parse this test expression. Fix to allow more checks.
                                                  ^-- SC1072 (error): Expected test to end here (don't wrap commands in []/[[]]). Fix any mentioned problems and try again.
```

2024-03-13 21:27 UTC, harryzcy commented
> Thanks! A small thing to fix:
> 
> ```shell
>             if [ ! grep -Fxq \\"${go_mod_filename}\\" \\"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO_MODULES\\" ]; then
>             ^-- SC1009 (info): The mentioned syntax error was in this if expression.
>                ^-- SC1073 (error): Couldn't parse this test expression. Fix to allow more checks.
>                                                   ^-- SC1072 (error): Expected test to end here (don't wrap commands in []/[[]]). Fix any mentioned problems and try again.
> ```

I have fixed the test

2024-03-20 09:13 UTC, ferrarimarco commented
There's an issue, I think:

```
  2024-03-13 21:41:06 [FATAL]   Error when setting INDEX for GO_MODULES: 0
```

https://github.com/super-linter/super-linter/actions/runs/8271680556/job/22632678543?pr=5345

Can you kindly take a look? Thanks!

2024-04-22 10:02 UTC, ferrarimarco commented
> There's an issue, I think:
> 
> ```
>   2024-03-13 21:41:06 [FATAL]   Error when setting INDEX for GO_MODULES: 0
> ```
> 
> https://github.com/super-linter/super-linter/actions/runs/8271680556/job/22632678543?pr=5345
> 
> Can you kindly take a look? Thanks!

More logs after rebasing:

```
  2024-04-22 09:49:46 [DEBUG]   PARALLEL_COMMAND_OUTPUT for GO_MODULES (exit code: 255): cd /tmp/lint/test/linters/go_modules/go_modules_good || exit 255; golangci-lint run --allow-parallel-runners -c /tmp/lint/.github/linters/.golangci.yml && echo \"Linted: /tmp/lint/test/linters/go_modules/go_modules_good\"
  parallel: Error: Cannot change into non-executable dir /tmp/lint/test/linters/go_modules/go_modules_good/go.mod: File exists
```

This is due to how we configure the command to run for `GO_MODULES`: https://github.com/super-linter/super-linter/blob/56e675bd333f8af069b2d7ba67ade1f39fcd01c4/lib/functions/worker.sh#L123-L139

So the command becomes:

```sh
parallel ... --workdir {} ...
```

(`{}` means: the input item as it is, which is `/tmp/lint/test/linters/go_modules/go_modules_good/go.mod` because you set it to `echo "${go_mod_filename}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO_MODULES"`).

I'll send another comment with the necessary changes.

Thanks for all your work on this!

2024-04-22 10:02 UTC, ferrarimarco requested changes

2024-04-25 22:28 UTC, harryzcy commented
@ferrarimarco Thanks for pointing out the issue! It's now updated

2024-04-26 11:13 UTC, ferrarimarco commented
Thanks!

We are on the right track!

I think we might still need some refactoring because in the current implementation users will not be able to disable lining of Go modules by using the `VALIDATE_GO_MODULES` variable. Also, we might report false positives because Go files might be linted one by one (`VALIDATE_GO` default mode), and also as a module.

Let me think a bit about this.

2024-04-26 20:53 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +        done
When walking up the directory, `potential_go_mod_file_path` here would not be changed? It should be updated within the loop for the parent `dir_name`

2024-04-26 20:56 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +      echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO"
Should line 394 be placed at line 391 instead? i.e. only lint individual Go files when it's not part of a Go module. I'm not sure here

2024-04-26 21:00 UTC, harryzcy commented
@ferrarimarco Thank you so much! There're two parts that I have doubts. If you agree, I'll make the edits and squash two commits.

2024-04-27 07:57 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO"
In this function, we just list and categorize files. Then, it's up to the user to eventually disable linting for individual Go files if they want to avoid false positives due to scanning individual files when there's a Go module. Before this change, we did checks in this regard, but it looked like a workaround and we had to account for a couple of corner cases about the test environment that complicated the logic when it wasn't necessary.

One check that we need anyway is that this should add `${FILE}` to `"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO"` only if it's a `.go` file, because `${FILE}` can be `go.mod`, and we don't want to add it to `file-array-GO`.

2024-04-27 07:59 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +        done
This is correct. We should update `potential_go_mod_file_path` after updating `dir_name`. Good catch

2024-04-27 08:00 UTC, ferrarimarco commented
Thanks for the review @harryzcy ! Your proposal SGTM :)

2024-04-27 16:31 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +      echo "${FILE}" >>"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO"
> One check that we need anyway is that this should add `${FILE}` to `"${FILE_ARRAYS_DIRECTORY_PATH}/file-array-GO"` only if it's a `.go` file, because `${FILE}` can be `go.mod`, and we don't want to add it to `file-array-GO`.

Updated in https://github.com/super-linter/super-linter/pull/5345/commits/cb8ebd42c9805a9f8b97bfacad0238be87e2d014

2024-04-27 16:31 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +        done
Fixed in https://github.com/super-linter/super-linter/pull/5345/commits/cb8ebd42c9805a9f8b97bfacad0238be87e2d014

2024-04-27 23:54 UTC, harryzcy commented
I just squashed two commits to become https://github.com/super-linter/super-linter/pull/5345/commits/4637a4ec70525882b1fdee2ccb977e2569d66180

2024-04-28 13:44 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      fi
Minor refactoring question. Do we want to move this echo in the else clause (L366) of the if if statement (L363)? That would perhaps make things clearer because we already have the relevant debug statements. WDYT?

2024-04-28 13:44 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      fi
@harryzcy

2024-04-30 12:00 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +      fi
done

2024-04-30 12:44 UTC, merged

2024-04-30 22:36 UTC, harryzcy commented on lib/functions/buildFileList.sh
> +      fi
thanks