Update README.md - editing the yaml example
super-linter/super-linter pull request #5452
Opened 2024-03-26 08:56 UTC by mohamedhamdyamer

adding:
permissions: read-all

This is to avoid failure of super-linter that is triggered by `checkov`.

`checkov` flags that the top-level permissions are set to "write-all" (default value). Accordingly, the action will fail with an error.

# Proposed changes

Small addition to the yaml example as described above

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [ ] I squashed all the commits into a single commit.
- [ ] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-03-26 18:05 UTC, ferrarimarco requested changes
Thanks for this PR! A small thing to check.

2024-03-26 18:05 UTC, ferrarimarco commented on README.md
> +    permissions: read-all # this is to avoid failure of super-linter that is triggered by checkov --> flagging that the top-level permissions are set to write-all (default value).
Can you remove the comment? It's an implementation detail :)

2024-03-27 07:56 UTC, mohamedhamdyamer commented on README.md
> +    permissions: read-all # this is to avoid failure of super-linter that is triggered by checkov --> flagging that the top-level permissions are set to write-all (default value).
sure

2024-03-27 08:52 UTC, mohamedhamdyamer commented on README.md
> +    permissions: read-all # this is to avoid failure of super-linter that is triggered by checkov --> flagging that the top-level permissions are set to write-all (default value).
Done,

Could you check, please?

2024-03-28 14:04 UTC, ferrarimarco approved these changes

2024-04-04 10:02 UTC, ferrarimarco requested changes

2024-04-04 10:02 UTC, ferrarimarco commented on README.md
> +    permissions: read-all
Can you please refactor this as `permissions: {}` instead?

We don't need the `read-all` permission.

Thanks!

2024-04-06 08:48 UTC, mohamedhamdyamer commented on README.md
> +    permissions: read-all
sure

2024-04-06 13:17 UTC, mohamedhamdyamer commented on README.md
> +    permissions: read-all
Done

2024-04-08 07:24 UTC, ferrarimarco approved these changes

2024-04-09 08:04 UTC, merged