Feat: add support for astral-sh/ruff
super-linter/super-linter pull request #5456
Opened 2024-04-01 09:46 UTC by Okabe-Junya

close #5384 

# Proposed changes

- add support for [astral-sh/ruff](https://github.com/astral-sh/ruff)

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [ ] I squashed all the commits into a single commit.
- [ ] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-04-03 10:15 UTC, ferrarimarco requested changes
Thanks for this PR! A couple of minor things to check. I'll also run CI workflows, and see what they say :)

2024-04-03 10:15 UTC, ferrarimarco commented on .github/linters/.ruff.toml
> +# Same as .flake8
This file is not needed because it's the same as the one in TEMPLATES

2024-04-03 10:15 UTC, ferrarimarco commented on TEMPLATES/.ruff.toml
> +ignore = ["E203"]
Why disable this one?

2024-04-03 13:10 UTC, Okabe-Junya commented on TEMPLATES/.ruff.toml
> +ignore = ["E203"]
In super-linter, E203 made disabled in #2821. I think that when supporting ruff, it should not contradict other tools that are already supported, such as black and flake8.

This means that the rule was disabled in order to avoid errors by ruff check (on code formatted with black)

2024-04-03 13:12 UTC, Okabe-Junya commented
Thank you @ferrarimarco for reviewing!!

I fixed CI error and commented. PTAL again, thank you 💙

2024-04-03 15:05 UTC, ferrarimarco commented on TEMPLATES/.ruff.toml
> +ignore = ["E203"]
Makes sense.

2024-04-03 15:06 UTC, ferrarimarco commented on README.md
> +| **PYTHON_RUFF_CONFIG_FILE**                     | `.ruff.toml`                    | Filename for [ruff configuration](https://docs.astral.sh/ruff/configuration/) (ex: `.ruff.toml`)
Can you remove `(ex: `.ruff.toml`) `? Not needed :)

2024-04-03 18:53 UTC, Okabe-Junya commented on README.md
> +| **PYTHON_RUFF_CONFIG_FILE**                     | `.ruff.toml`                    | Filename for [ruff configuration](https://docs.astral.sh/ruff/configuration/) (ex: `.ruff.toml`)
deleted!!

2024-04-03 18:55 UTC, Okabe-Junya commented on lib/linter.sh
> +  'PYTHON_FLAKE8' 'PYTHON_ISORT' 'PYTHON_MYPY' 'PYTHON_RUFF'
I missed adding `'PYTHON_RUFF'` in this section, so now I believe **ALL** CI is passing ...

2024-04-04 10:00 UTC, ferrarimarco requested changes
@Okabe-Junya we're almost there!

As a last change, can you please make the tests shorter? There's likely no need to include these big files. Maybe 3-4 lines each are enough.

Thanks!

2024-04-04 20:02 UTC, Okabe-Junya commented
Thank you @ferrarimarco

Your review is very sensible. However, other Python tools are (mostly) using the same test files. I think we should not prepare a completely different test file just for ruff now.

FYI: 

- black: https://github.com/super-linter/super-linter/tree/main/test/linters/python_black
- pylint: https://github.com/super-linter/super-linter/tree/main/test/linters/python_pylint
- flake8: https://github.com/super-linter/super-linter/tree/main/test/linters/python_flake8
- mypy: https://github.com/super-linter/super-linter/tree/main/test/linters/python_mypy

Meaning, if we are to change to test files of about 3-4 lines, shouldn't we do the same for the other files as well? And, I think this change is beyond the scope of this PR.

thank you 💙

2024-04-05 06:40 UTC, ferrarimarco commented
> Thank you @ferrarimarco
> 
> Your review is very sensible. However, other Python tools are (mostly) using the same test files. I think we should not prepare a completely different test file just for ruff now.
> 
> FYI:
> 
> * black: https://github.com/super-linter/super-linter/tree/main/test/linters/python_black
> * pylint: https://github.com/super-linter/super-linter/tree/main/test/linters/python_pylint
> * flake8: https://github.com/super-linter/super-linter/tree/main/test/linters/python_flake8
> * mypy: https://github.com/super-linter/super-linter/tree/main/test/linters/python_mypy
> 
> Meaning, if we are to change to test files of about 3-4 lines, shouldn't we do the same for the other files as well? And, I think this change is beyond the scope of this PR.
> 
> thank you 💙

Hi! There's no need for the test files to be aligned. In fact, we should reduce the size of the others as well, but this is out of scope for this PR, as you said. We can start with these ones, tho.

Thanks for your contributions!

2024-04-05 07:35 UTC, Okabe-Junya commented
Thanks!!

> but this is out of scope for this PR, as you said. We can start with these ones, tho.

I would like to work on updating the test files after this PR is merged :)

First, I will focus on merging this PR. I think that addressing the CI errors is what needs to be done. I will investigate the cause of the CI failures...

2024-04-05 07:39 UTC, ferrarimarco commented
Sorry, I mistyped. I meant: we can start with the ones in this PR. :)

thanks a lot!

2024-04-05 07:47 UTC, Okabe-Junya reviewed
I have investigated similar PRs to resolve CI error. #4925 seems to be one of them.

Upon careful investment, I realized that I did not write code like `LINTER_NAMES_ARRAY['CHECKOV']="checkov"`. However, such code does not exist in `lib/linter.sh`.

When I used "grep" to check the code, I found that it had been moved to `scripts/linterVersions.sh` in #5197. This means that I need to make a simple modification to `scripts/linterVersions.sh`.

2024-04-05 07:49 UTC, Okabe-Junya commented
I believe now **ALL** CI will pass...

2024-04-05 09:18 UTC, ferrarimarco commented on scripts/linterVersions.sh
> +LINTER_NAMES_ARRAY['PYTHON_RUFF']="ruff"
I think you may need to add the `ruff --version` special case below. The default command is `LINTER_NAME -v`.

2024-04-05 09:19 UTC, ferrarimarco commented on test/linters/python_ruff/python_bad_1.py
> +import json
As we mentioned, can you please reduce this file to be smaller? 3-4 lines should be enough. It's ok if it's not aligned to the test files we're using for other Python linters. Actually, we don't want that dependency. :)

Thanks!

2024-04-05 09:20 UTC, ferrarimarco commented on test/linters/python_ruff/python_good_1.py
> +import json
As we mentioned, can you please reduce this file to be smaller? 3-4 lines should be enough. It's ok if it's not aligned to the test files we're using for other Python linters. Actually, we don't want that dependency. :)

Thanks!

2024-04-05 09:22 UTC, Okabe-Junya commented on scripts/linterVersions.sh
> +LINTER_NAMES_ARRAY['PYTHON_RUFF']="ruff"
https://github.com/super-linter/super-linter/blob/dec3f48f49948d292f99953db549811f65e762c9/test/inspec/super-linter/controls/super_linter.rb#L186

I think it can be configured in this section, so I don't need to change..

2024-04-05 09:25 UTC, Okabe-Junya commented on test/linters/python_ruff/python_bad_1.py
> +import json
My apologies,  I misunderstood a bit. Ok, I'll fix it :)

2024-04-05 10:07 UTC, Okabe-Junya commented on test/linters/python_ruff/python_bad_1.py
> +import json
I fixed it!!

2024-04-05 10:07 UTC, Okabe-Junya commented on test/linters/python_ruff/python_good_1.py
> +import json
I fixed it!!

2024-04-05 10:22 UTC, Okabe-Junya commented
I have fixed to the test files, and all CI checks have passed in the forked repo!!

FYI: https://github.com/Okabe-Junya/super-linter/actions/runs/8568038203

<img width="1512" alt="Screenshot 2024-04-05 at 19 18 04" src="https://github.com/super-linter/super-linter/assets/86868255/f99b3685-e497-4f6e-81f8-c24214ec64c8">

2024-04-05 12:13 UTC, ferrarimarco commented on scripts/linterVersions.sh
> +LINTER_NAMES_ARRAY['PYTHON_RUFF']="ruff"
The one in `super_linter.rb` is for running tests. The one I'm referring to is to generate the versions file. So, you need both :)

Thanks!

2024-04-05 12:21 UTC, ferrarimarco commented on scripts/linterVersions.sh
> +LINTER_NAMES_ARRAY['PYTHON_RUFF']="ruff"
Ok, inspected `linterVersions.sh` once more. There's no need to add a special case here because the default is to use the `--version` switch.

2024-04-05 12:24 UTC, ferrarimarco commented
One small thing to check and we should be good to go! Thanks for all this work @Okabe-Junya !

2024-04-05 13:01 UTC, Okabe-Junya commented
Thank you for reviewing this many times. I have checked!

2024-04-09 07:34 UTC, ferrarimarco approved these changes

2024-04-10 12:12 UTC, merged

2024-04-10 17:51 UTC, Okabe-Junya commented
Thank you for your Considerate and kind support 💙 Looking forward to release!!

2024-04-10 18:08 UTC, Okabe-Junya commented on test/linters/python_ruff/python_good_1.py
> +import json
created #5501, thank you!!