Update Python Test Files
super-linter/super-linter pull request #5502
Opened 2024-04-10 18:15 UTC by Okabe-Junya

# Proposed changes

- align python test files to ruff.

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [ ] I squashed all the commits into a single commit.
- [ ] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-04-11 13:07 UTC, ferrarimarco requested changes
Hi @Okabe-Junya !

Thanks for this PR.

A small thing to check, so we can run the rest of the CI jobs.

2024-04-15 04:49 UTC, Okabe-Junya commented on test/linters/python_isort/python_bad_1.py
> -import sys
Oh, sorry for my missed operation.

isort checks the `import ...` or `from ... import ...` statements, so I shouldn't have removed this part. I have fixed it. It seems that the CI is passing now, except for the preview release note.

2024-04-15 04:51 UTC, Okabe-Junya commented
Hi @ferrarimarco, thank you for your review!! And, sorry for my delay in response.

I checked your review comment and fixed it!! Please take a look again 💙 thanks!!

2024-04-15 12:00 UTC, ferrarimarco commented
No worries, thanks for this work!

2024-04-15 12:01 UTC, ferrarimarco approved these changes

2024-04-15 12:07 UTC, merged

2024-04-15 12:36 UTC, Okabe-Junya commented
Thank you for your kind supports!!