Include Helm for checkov scans
super-linter/super-linter pull request #5631
Opened 2024-05-09 14:56 UTC by andrewkreuzer

# Proposed changes

Includes Helm for the running of checkov scans with the helm framework

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [ ] I squashed all the commits into a single commit.
- [ ] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-05-09 19:23 UTC, ferrarimarco commented
Hi @andrewkreuzer ! Thanks for this PR.

What problem are we solving here? :)

2024-05-09 19:31 UTC, andrewkreuzer commented
when running checkov using the "helm" framework I wasn't seeing scans being done for my helm charts. Running locally I was able to get the desired output:
```
helm scan results:
   Passed checks: 233, Failed checks: 0, Skipped checks: 0
```
but wasn't seeing this output with superlinter

Running checkov in the superlinter container `checkov --framework helm --var-file my-values.yaml --directory charts` I was able to get to this error: 
```
2024-05-09 14:17:51,287 [MainThread  ] [ERROR]  There are no runners to run. This can happen if you specify a file type and a framework that are not compatible (e.g., `--file xyz.yaml --framework terraform`), or if you specify a framework with missing dependencies (e.g., helm or kustomize, which require those tools to be on your system). Running with LOG_LEVEL=DEBUG may provide more information.
```

2024-05-09 19:35 UTC, ferrarimarco commented
I see, thanks for the details!

2024-05-09 19:41 UTC, ferrarimarco requested changes
Thanks for this PR!

Besides this, we would need some test cases (good and bad ones) in this dir: https://github.com/super-linter/super-linter/tree/main/test/linters/checkov

2024-05-09 19:41 UTC, ferrarimarco commented on Dockerfile
> +    && rm -rfv /install-helm.sh
To have more controls over dependency updates, can you refactor this to grab helm from a container image?

Maybe this one https://hub.docker.com/r/alpine/helm

TLDR: Add a FROM statement near the others (see the top of this file), and copy the relevant binaries from that.

Also, that image appears to be a multi-platform image, so this will help when we'll eventually support arm64

2024-05-09 19:41 UTC, ferrarimarco commented on scripts/install-helm.sh
> +#!/usr/bin/env bash
If we install helm from that container image, we don't need this script.

2024-05-09 19:44 UTC, andrewkreuzer commented on Dockerfile
> +    && rm -rfv /install-helm.sh
ya can do, I was trying to find an image built by the helm team but couldn't find one, I can use that one though!

2024-05-12 13:24 UTC, ferrarimarco commented
One minor change: can you please make the test helm charts smaller? We don't need to have a fully working chart as a test case. What we need is the bare minimum to have tests pass :)

Thanks!

2024-05-29 13:59 UTC, andrewkreuzer commented
@ferrarimarco reduced the size of the test charts hopefully that is small enough

2024-06-04 13:45 UTC, andrewkreuzer commented
> @andrewkreuzer Thanks, the new test cases seems to be picked up. Nice!
> 
> Quick question: do the `good` test cases fail if you don't install helm? Just to confirm that we're covering this case as well.
> 
> Thanks!

no checkov will simple not run the helm checks if it can't find the helm binary

2024-06-05 07:31 UTC, ferrarimarco commented
SGTM, I just found a reference about this in the [Checkov docs](https://www.checkov.io/7.Scan%20Examples/Helm.html)

2024-06-05 07:31 UTC, ferrarimarco approved these changes

2024-06-05 07:36 UTC, ferrarimarco requested changes
Thanks a lot for all the work here.

We need just two more quick things about this in the test suite, and we should be good to go.

2024-06-05 07:36 UTC, ferrarimarco commented on Dockerfile
> +COPY --from=helm /usr/bin/helm /usr/bin/
Can you add an entry for `helm` in the

- [linters list](https://github.com/super-linter/super-linter/blob/88ea3923a7e1f89dd485d079f6eb5f5e8f937589/test/inspec/super-linter/controls/super_linter.rb#L134), so we exercise it at least once? Please also add a comment explaining that this is not a linter, but we need it for Checkov.
- [files list](https://github.com/super-linter/super-linter/blob/88ea3923a7e1f89dd485d079f6eb5f5e8f937589/test/inspec/super-linter/controls/super_linter.rb#L459), so we check for its existence.

2024-06-06 18:54 UTC, ferrarimarco requested changes

2024-06-06 18:54 UTC, ferrarimarco commented on test/inspec/super-linter/controls/super_linter.rb
> +    { linter_name: "helm"}, # not used as linter, needed for checkov's helm framework
Please, refactor this to `{ linter_name: "helm", version_option: "version"}` to fix the InSpec error.

Thanks!

2024-06-07 15:06 UTC, ferrarimarco approved these changes

2024-06-07 15:30 UTC, merged