New GitLab CI Component
super-linter/super-linter pull request #5675
Opened 2024-05-21 20:44 UTC by DarwinJS

# Proposed changes

GitLab CI Components are a new way of extending GitLab with community authored components.

This MR points to the new GitLab CI Component I created to make it super simple to consume Super Linter on GitLab everywhere :)

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [X] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [X] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` label to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.

2024-05-23 11:53 UTC, ferrarimarco commented
Hi @DarwinJS !

I'm not familiar with GitLab components.

Can you host them outside GitLab, or do they have to be GitLab repositories?

2024-05-23 12:47 UTC, ferrarimarco requested changes
Thanks for this PR.

This reminded me that we have a few outdated references on this page. I'm addressing this in a separate PR (#5677).

After #5677, can you rebase this on the top of `main`?

Thanks!

2024-05-23 12:47 UTC, ferrarimarco commented on README.md
> +## Get started with GitHub
Can you revert this change?

2024-05-23 12:47 UTC, ferrarimarco commented on README.md
> +
Can you revert this change? Those are GitLab-specific assets that should be addressed in the component's README.

2024-05-23 12:47 UTC, ferrarimarco commented on docs/run-linter-locally.md
> +Check out this GitLab CI Component which only requires a single line of code: [GitLab CI Component for Super-Linter](https://gitlab.com/explore/catalog/guided-explorations/ci-components/super-linter)
We should refactor this sentence to avoid confusion, given that you used the `super-linter` namespace in GitLab, which might lead to readers thinking that the component is part of Super-linter, which is not. Also, it would be nice to add something along these lines to the component's README as well.

Can you refactor this sentence to:

Alternatively, you can [this GitLab CI/CD component](https://gitlab.com/explore/catalog/guided-explorations/ci-components/super-linter). Note that this component is not designed, implemented, or maintained by Super-linter's maintainers.

2024-05-30 10:30 UTC, DarwinJS commented on README.md
> +
Ok. I was under the impression the project was trying to be completely open source - so not necessarily a preference for GitHub? So was hoping improve the visibility since the mentions in [run-linter-locally.md](https://github.com/super-linter/super-linter/pull/5675/files/b255c05e095759bd3d3691ed4ce46c5375e9399b#diff-dcff84bdfaded6e195b1777747de2b7a40f3eb8752361658c671e3b009d40656) are rather off the beaten path?

Was also putting "how to include" information on parity with GitHub? Brief, but complete enough for quick success.

2024-05-30 10:31 UTC, DarwinJS commented on docs/run-linter-locally.md
> +Check out this GitLab CI Component which only requires a single line of code: [GitLab CI Component for Super-Linter](https://gitlab.com/explore/catalog/guided-explorations/ci-components/super-linter)
Sure - I was just following what was there. So is this out of the way place the only allowable mention of the GitLab support then?

2024-06-05 07:52 UTC, ferrarimarco commented on README.md
> +
Given that the vast majority of users run this on GitHub Actions, for now we can keep this in the `run-linter-locally.md` file. If we get more traction from GitLab users, we can revisit this.

2024-06-05 07:56 UTC, ferrarimarco commented
> > Hi @DarwinJS !
> > I'm not familiar with GitLab components.
> > Can you host them outside GitLab, or do they have to be GitLab repositories?
> 
> They have to hosted on a GitLab Instance - but not necessarily GitLab.com. They can be included into GitLab CI jobs that have access to the component (including on runners not associated with the hosting gitlab instance if the component is public).

Got it, thanks!

2024-07-20 00:11 UTC, closed without merging