chore: simplified `awk` usage for version extraction
super-linter/super-linter pull request #5893
Opened 2024-07-15 14:45 UTC by fearphage

# Proposed changes

Simplified version extract from Gradle files from 3 calls to 1. 

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [ ] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [ ] I squashed all the commits into a single commit.
- [x] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches with the version that release-please proposes.

2024-07-31 11:40 UTC, ferrarimarco requested changes
Thanks for this PR! A couple of small things to check.

2024-07-31 11:40 UTC, ferrarimarco commented on docs/add-new-linter.md
> +        GOOGLE_JAVA_FORMAT_VERSION="$(awk -F "[:']" '/google-java-format/ {print $3}' "google-java-format/build.gradle")"
`print $3` -> `print $4`

2024-07-31 11:40 UTC, ferrarimarco commented on docs/add-new-linter.md
> +        GOOGLE_JAVA_FORMAT_VERSION="$(awk -F "[:']" '/google-java-format/ {print $3}' "google-java-format/build.gradle")"
Can you refactor this to:

```
GOOGLE_JAVA_FORMAT_VERSION="$(
  set -euo pipefail
  awk -F "[:']" '/google-java-format/ {print $4}' "google-java-format/build.gradle"
)"

2024-09-14 07:59 UTC, fearphage commented on docs/add-new-linter.md
> +        GOOGLE_JAVA_FORMAT_VERSION="$(awk -F "[:']" '/google-java-format/ {print $3}' "google-java-format/build.gradle")"
Updated.

2024-09-27 07:59 UTC, ferrarimarco approved these changes

2024-09-27 07:59 UTC, merged

2024-09-27 07:59 UTC, ferrarimarco commented
Thanks for this PR!