fix: Update pylint to ignore import-errors
super-linter/super-linter pull request #5927
Opened 2024-07-25 12:47 UTC by Shop-kins

Adds back import-error to the pylint disable rules that was removed as of: https://github.com/super-linter/super-linter/pull/5252

`Fix #5926`

# Proposed changes

update .python-lint to include `disable=import-error`

Also adds a new test case for import errors

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [ ] I included all the needed documentation for this change.
- [X] I provided the necessary tests.
- [X] I squashed all the commits into a single commit.
- [X] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [N/A] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [X] If this pull request is about and existing issue,
- [X] I added the `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches with the version that release-please proposes.

2024-07-25 13:00 UTC, ferrarimarco requested changes
Thanks for this PR. A small thing to check.

2024-07-25 13:00 UTC, ferrarimarco commented on TEMPLATES/.python-lint
> +disable=import-error
Can you add a comment to explain why we need to disable this check?

Also, can you remove the explanation about how to use the `disable` directive? We don't need to repeat pylint docs. 😀

2024-07-25 13:01 UTC, Shop-kins commented on TEMPLATES/.python-lint
> +disable=import-error
Will Do!

2024-07-25 13:05 UTC, Shop-kins commented on TEMPLATES/.python-lint
> +disable=import-error
have pushed a change for this :)

2024-07-26 14:29 UTC, ferrarimarco commented
Thanks!

2024-07-28 15:19 UTC, ferrarimarco commented
Thanks for the update.

The builds are failing because:

1. the commit message has a capital letter.
1. There's an [ad-hoc configuration file that we use for pylint when it runs against the super-linter codebase](https://github.com/super-linter/super-linter/blob/main/.github/linters/.python-lint) that we should either update, or remove.

Can you please fix the commit message?

Meanwhile, I'll check if we need that second configuration file or not.

2024-07-28 15:43 UTC, ferrarimarco commented on TEMPLATES/.python-lint
We don't need the super-linter specific configuration file anymore. Can you please delete `.github/linters/.python-lint` as part of this PR?

Thanks!

2024-07-28 15:55 UTC, ferrarimarco commented on TEMPLATES/.python-lint
Actually, let me do that in a separate PR.

2024-07-28 17:47 UTC, ferrarimarco commented
By rebasing on top of the latest `main`, the pylint check should now pass.

2024-07-29 08:50 UTC, Shop-kins commented
> By rebasing on top of the latest `main`, the pylint check should now pass.

Have rebased and removed the capitals!

2024-07-29 17:20 UTC, ferrarimarco commented
Thanks!

2024-07-30 06:26 UTC, ferrarimarco requested changes
A minor thing to fix, and we shall be good to go!

Thanks for this work :)

2024-07-30 06:26 UTC, ferrarimarco commented on test/linters/python_pylint/python_good_2.py
> +import pytest
We only have two minor linting errors on this file:

```
  test/linters/python_pylint/python_good_2.py:3:13: C0303: Trailing whitespace (trailing-whitespace)
  test/linters/python_pylint/python_good_2.py:1:0: C0114: Missing module docstring (missing-module-docstring)
```

Can you please fix both?

2024-07-31 07:03 UTC, ferrarimarco commented on test/linters/python_pylint/python_good_2.py
> +import pytest
Done

2024-07-31 07:26 UTC, ferrarimarco approved these changes

2024-07-31 07:27 UTC, merged