Add ability to configure PHPStan via `PHP_PHPSTAN_CONFIG_FILE`.
super-linter/super-linter pull request #5940
Opened 2024-07-30 05:48 UTC by shabbir-genetech

# Proposed changes

Add ability to configure PHPStan via `PHP_PHPSTAN_CONFIG_FILE`.

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [ ] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [ ] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches with the version that release-please proposes.

2024-07-30 06:33 UTC, ferrarimarco requested changes
Thanks for this PR! I think we just need to adjust the commit message, and we shall be good to go. Something like:

`feat: customize phpstan config file name`

2024-07-30 14:22 UTC, ferrarimarco approved these changes

2024-07-30 14:38 UTC, merged

2024-07-31 07:14 UTC, shabbir-genetech commented
@ferrarimarco Can you advise on when the next release might be released which will include this change? Is there a way to use it right now in GitHub actions? I tried `uses: super-linter/super-linter@latest` but that still seems to pull ghcr.io/super-linter/super-linter:v6.7.0 .

2024-07-31 08:22 UTC, ferrarimarco commented
Hi @shabbir-genetech !

I think we can release one over the course of this week, since it's long due.

> uses: super-linter/super-linter@latest but that still seems to pull ghcr.io/super-linter/super-linter:v6.7.0

This is expected. We currently point the `latest` action to the most recently released version, not to the `latest` container image because that might be less stable than a released version.

As a workaround, you can still name your PHPStan rules file as `phpstan.neon`. Super-linter will pick it up.

Thanks for your work here!