docs: update the supported linters table
super-linter/super-linter pull request #5971
Opened 2024-08-05 13:57 UTC by rindeal

# Proposed changes

Some PRs introduced a new linter, but didn't update the table, like for example https://github.com/super-linter/super-linter/pull/1401. Some PRs simultaneously added a linter along with a table update, but also removed the table update in the next commit of the same PR like https://github.com/super-linter/super-linter/pull/450. Some entries had very outdated links. Some were sorted in a wrong alphabetical order.

The code I used to make this update possible:
https://github.com/super-linter/super-linter/blob/0dbe14433636762a7001dfe1e96d2518d73f774d/scripts/linterVersions.sh#L6-L91 https://github.com/super-linter/super-linter/blob/0dbe14433636762a7001dfe1e96d2518d73f774d/lib/functions/buildFileList.sh#L203-L539
## Readiness checklist

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue,
  I added the `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of the pull request.

### Super-linter maintainer tasks

- [x] Label as `breaking` if this change breaks compatibility with the previous released version.
- [x] Label as either: `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches with the version that release-please proposes.

2024-08-07 13:36 UTC, ferrarimarco commented
Thanks for this PR.

Can you please revert the formatting changes, and just update the items in the table? Otherwise it gets quite difficult to review due to the size of the change. Thanks!

2024-08-07 17:46 UTC, Hanse00 reviewed
I have a few comments / suggestions as outlined here, but I also just wanted to say: Thank you! For putting in the effort to try to improve our documentation. It's great to see involvement from the wider community in making the tool better.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> -| **Azure Resource Manager (ARM)** | [arm-ttk](https://github.com/azure/arm-ttk)
I would keep (ARM), my experience suggests some folks use that term fairly exclusively and wouldn't realize Azure Resource Manager is the same thing.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**C/C++**                        | [cpplint](https://github.com/cpplint/cpplint) / [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
I'm not a C developer, but is it accurate that cpplint can also lint C? Or should this be broken out?

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**CoffeeScript**                 | [coffeelint](https://github.com/coffeelint/coffeelint)
What's the rationale behind the decision to point this at the source rather than the webpage?

I'm not saying I neccesarily disagree, but I'd like to hear the logic.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**Go**                           | [golangci-lint](https://github.com/golangci/golangci-lint)
I don't have a very strong opinion here, but personally I lean towards the Golang moniker.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**GoReleaser**                   | [goreleaser](https://github.com/goreleaser/goreleaser)
Again i don't have a super strong opinion, but I would lean towards formatting the name of a tool the way the authors do. The README file in the repo seem to suggest GoReleaser is the correct formatting.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**Infrastructure as Code**       | [Checkov](https://www.checkov.io/)
It might be annoying to do, but I would prefer listing which IaC languages/tools are supported. Just naming the whole category feels a little wishy-washy.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**JSON**                         | [ESLint](https://eslint.org/) with [JSON plugin](https://www.npmjs.com/package/eslint-plugin-json)
Above you changed from a "marketing" name (GoReleaser) to a normalized form, here you're doing the opposite. As far as I can tell, the correct name for the plugin is in fact "eslint-plugin-json". I would stick with that unless the docs actually refer to the plugin as "JSON plugin" somewhere.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**Python**                       | [pylint](https://pylint.pycqa.org/) / [flake8](https://flake8.pycqa.org/en/latest/) / [black](https://github.com/psf/black) / [isort](https://pycqa.github.io/isort/
Do these tools also support Python 2?

I could see an argument on both sites as far as whether it's worth highlighting that distinction in the year 2024. Perhaps nobody* uses Py2 anymore?

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +**Amazon States Language**       | [asl-validator](https://www.npmjs.com/package/asl-validator)
This probably belongs further up if we're trying to go in alphabetical order.

2024-08-07 17:46 UTC, Hanse00 commented on README.md
> +\* Denotes linters available only in the standard image.
I would invert this statement, something like: Linters unavailable in the slim image.

2024-08-12 10:30 UTC, ferrarimarco requested changes
Hi! Just some small names to fix, and we should be good to go.

Please, update the commit message so it passes validation. Maybe:

`docs: update the supported linters table`

Thanks!

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Azure Resource Manager (ARM)** | [ARM TTK](https://github.com/azure/arm-ttk) \*
ARM TTK -> Azure Resource Manager Template Toolkit (arm-ttk)

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Azure Resource Manager (ARM)** | [ARM TTK](https://github.com/azure/arm-ttk) \*
Remove `\*`

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**C/C++**                        | [CPPLint](https://github.com/cpplint/cpplint), [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
CPPLint -> cpplint

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**C#**                           | [dotnet format](https://github.com/dotnet/format) \*, [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
Remove `\*`

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**C#**                           | [dotnet format](https://github.com/dotnet/format) \*, [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
Remove `, [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)` because  Super-linter doesn't use Clang-Format to format C# files (yet?)

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**CSS/SCSS/Sass/Less**           | [Stylelint](https://github.com/stylelint/stylelint)
Remove `Less` because Super-linter doesn't (yet?) lint `.less` files with Stylelint.

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Dart**                         | [Dart Analyzer](https://dart.dev/tools/dart-analyze)
Dart Analyzer -> dart analyze

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Dockerfile**                   | [Hadolint](https://github.com/hadolint/hadolint)
Hadolint -> Haskell Dockerfile Linter (Hadolint)

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**EditorConfig**                 | [EditorConfig Checker](https://github.com/editorconfig-checker/editorconfig-checker)
EditorConfig Checker -> editorconfig-checker

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Go**                           | [GolangCI-Lint](https://github.com/golangci/golangci-lint)
GolangCI-Lint -> golangci-lint

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Java**                         | [Checkstyle](https://checkstyle.org), [Google Java Format](https://github.com/google/google-java-format)
Google Java Format -> google-java-format

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**JSON**                         | [ESLint Plugin JSON](https://www.npmjs.com/package/eslint-plugin-json)
ESLint Plugin JSON -> eslint-plugin-json

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**JSONC**                        | [ESLint Plugin JSONC](https://www.npmjs.com/package/eslint-plugin-jsonc)
ESLint Plugin JSONC -> eslint-plugin-jsonc

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**JSON**                         | [ESLint Plugin JSON](https://www.npmjs.com/package/eslint-plugin-json)
Can you please add: `, [eslint-plugin-jsonc](https://www.npmjs.com/package/eslint-plugin-jsonc) configured for JSON`

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**JSONC**                        | [ESLint Plugin JSONC](https://www.npmjs.com/package/eslint-plugin-jsonc)
Can you add `JSON5` to the first column?

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Markdown**                     | [Markdownlint](https://github.com/igorshubovych/markdownlint-cli#readme)
Remove `#readme` for consistency with other links.

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**PowerShell**                   | [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) \*
Remove `\*`

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +**Rust**                         | [Rustfmt](https://github.com/rust-lang/rustfmt) \*, [Clippy](https://github.com/rust-lang/rust-clippy) \*
Remove both `\*`

2024-08-12 10:30 UTC, ferrarimarco commented on README.md
> +\* Denotes linters not available in the _slim_ image.
Remove this because we already have this information in https://github.com/super-linter/super-linter?tab=readme-ov-file#super-linter-variants

2024-08-15 09:45 UTC, ferrarimarco commented
Can you also please rebase against `main` and resolve conflicts? We recently applied some formatting fixes to the README.

Thanks!

2024-08-16 06:19 UTC, ferrarimarco commented
No worries!

2024-08-16 12:55 UTC, ferrarimarco commented
See #6038

2024-08-16 12:55 UTC, closed without merging