feat: Add Python Blacken Docs
super-linter/super-linter pull request #6243
Opened 2024-10-09 17:49 UTC by holtskinner

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [ ] I checked that all workflows return a success.
- [X] I included all the needed documentation for this change.
- [X] I provided the necessary tests.
- [X] I squashed all the commits into a single commit.
- [X] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [ ] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

2024-10-10 10:26 UTC, ferrarimarco commented on lib/globals/languages.sh
> +  'PHP_PSALM' 'POWERSHELL' 'PROTOBUF' 'PYTHON_BLACK' 'PYTHON_BLACKEN_DOCS' 'PYTHON_PYLINT'
Can you move `PYTHON_BLACKEN_DOCS` to a new line, and use double quotes? we're trying to move in that direction in this array.

2024-10-10 10:27 UTC, ferrarimarco commented on scripts/linterVersions.sh
> +LINTER_NAMES_ARRAY['PYTHON_BLACKEN_DOCS']="blacken-docs"
You need to add this to the `PATH`. I realized that we're missing this point from the instructions. Addressed in #6244

2024-10-17 08:27 UTC, ferrarimarco requested changes
Thanks for this PR.

I don't have experience with `blacken-docs`. From what I understand, it supports formatting Python code inside documentation files, and currently supports:

- Markdown
- reStructuredText
- LaTeX

Also, from blacken-docs readme:

> Additionally, you can run it on Python files to reformat Markdown and reStructuredText within docstrings.

It seems like this is the use case that we're trying to address here, because I don't see other file types besides Python files in the addition to `buildFileList.sh`

Do you know if this has any potential conflicts with Black?

Do you know if blacken-docs has evidence of being maintained? It looks like that it was just recently (~2 months ago) picked up after a 1 year pause, at least in terms of releases.

2024-10-17 08:27 UTC, ferrarimarco commented on scripts/linterVersions.sh
>  #!/usr/bin/env bash
The updates to this file might be the result of an over-conservative rebase. Can you revert all the unrelated changes, and the duplicate lines that this change is trying to add?

2024-10-17 08:27 UTC, ferrarimarco commented on scripts/linterVersions.sh
> +  elif [[ ${LINTER} == "bash-exec" ]] || [[ ${LINTER} == "blacken-docs" ]] || [[ ${LINTER} == "gherkin-lint" ]]; then
I had a quick look at blacken-docs, and it doesn't appear to support an option to get its version. Can you please open an issue in their repository asking for that?

Thanks!

2024-10-24 19:59 UTC, ferrarimarco commented
It seems that there are potential conflicts with Black, unfortunately. And blacken-docs doesn't appear to support a configuration file either.

https://github.com/adamchainz/blacken-docs/issues/62

2024-11-01 19:49 UTC, holtskinner commented
> It seems that there are potential conflicts with Black, unfortunately. And blacken-docs doesn't appear to support a configuration file either.
> 
> [adamchainz/blacken-docs#62](https://github.com/adamchainz/blacken-docs/issues/62)

Ok, that's good to know... I suppose it doesn't make sense to add it into Superlinter at this time. I'll go ahead and close this out and remove blacken-docs from #6240

2024-11-01 19:49 UTC, closed without merging

2024-11-02 09:42 UTC, ferrarimarco commented
Thanks for the update, and sorry for the extra work!