Update run-linter-locally.md
super-linter/super-linter pull request #6326
Opened 2024-11-07 17:21 UTC by JLLeitschuh

## Readiness checklist

Resolves #5472

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [ ] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

2024-11-07 20:32 UTC, ferrarimarco commented
Hi, thanks for this PR.

Isn't this covered by the README already?

2024-11-07 21:01 UTC, JLLeitschuh commented
I ended up missing it and didn't see it until I looked at the issue #5472. I figure putting the relevant information closer would be helpful. This isn't really "needed" but more "useful".

2024-11-15 21:00 UTC, ferrarimarco commented on docs/run-linter-locally.md
> +  the default branch name for your repository set the `DEFAULT_BRANCH` environment variable.
Please refactor this as follows so we don't need to maintain the same information in two different places (here and in the main README). Thanks:

You can use the `DEFAULT_BRANCH` variable to set the default branch. For more information about its default value, see the main README.

2024-11-15 21:04 UTC, ferrarimarco requested changes
Also, please refactor the commit message to:

> docs: mention default_branch when running locally

Thanks!

2025-02-20 18:02 UTC, ferrarimarco commented on docs/run-linter-locally.md
> +  the default branch name for your repository set the `DEFAULT_BRANCH` environment variable.
@JLLeitschuh Ping :) thanks for refactoring.

2025-02-21 14:20 UTC, ferrarimarco approved these changes

2025-02-23 17:44 UTC, merged