Fixed Broken link on SQLFLUFF configuration #6474
super-linter/super-linter pull request #6475
Opened 2024-12-31 15:40 UTC by yuya-hanzawa

## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [x] I checked that all workflows return a success.
- [x] I included all the needed documentation for this change.
- [x] I provided the necessary tests.
- [x] I squashed all the commits into a single commit.
- [x] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [x] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [ ] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [ ] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [ ] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

2025-01-09 09:22 UTC, ferrarimarco requested changes
Thanks for this PR. One minor change: can you please refactor the commit message to:

```
docs: fix broken link to sqlfluff config
```

Thanks!

2025-01-10 09:06 UTC, yuya-hanzawa commented
@ferrarimarco
Thanks for the feedback!
I've updated the commit message as requested.
Please let me know if there's anything else you'd like me to adjust.

2025-01-10 09:27 UTC, ferrarimarco commented
There's a minor formatting issue in the main README after this update. Can you please check that?

If you're building the container image locally, you can follow https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md#automatically-fix-formatting-and-linting-issues, or you can run Prettier manually.

Thanks!

2025-01-10 16:34 UTC, yuya-hanzawa commented
@ferrarimarco
I apologize for the inconvenience, and thank you for your comment.

It seems the error was caused by a misalignment in the table's indentation when I fixed the link.
I was able to resolve the issue using the method you shared. Thank you!

2025-01-10 17:41 UTC, ferrarimarco approved these changes
Thanks!

2025-01-13 21:17 UTC, merged